### ISSUE TITLE
KeyError: 'pg_timestamp'

### ISSUE THREAD

**Issue by Kira-PH** [Komzpa/furry-sansa#7]
At the end of import, I get this:

```
Completed planet_osm_polygon

Osm2pgsql took 2638s overall
Traceback (most recent call last):
  File "./furry.py", line 74, in <module>
    if os.path.exists(instance['pg_timestamp']):
KeyError: 'pg_timestamp'
```

**Comment by Komzpa** [comment]
That's supposed to be a file that is mentioned in config and holds import timestamp. Which config do you use?
```
    'pg_timestamp':     '/home/gis/planet_osm_pg.timestamp', # timestamp of database import
```

**Comment by Kira-PH** [comment]
Hey, thanks for the quick reply :)

I did have that, and removed it because I had some other error where it barfed early because it couldn't find that file - because obviously it hadn't been created yet. I think it was during synthdump.

(I've just started import again with that line uncommented - and an appropriate path)

**Comment by Komzpa** [comment]
that could have been getdiff, but it's not supposed to be run before you finished your first import.

**Comment by Kira-PH** [comment]
I've been following your readme.md
I did synthdump, followed by import and then index.

index doesn't work with the openstreetmap-carto style and/or tag processing script (probably the latter)

**Comment by Kira-PH** [comment]
Interestingly, I still get the message:
```
Osm2pgsql took 2775s overall
Traceback (most recent call last):
  File "./furry.py", line 77, in <module>
    if "(" in open(instance['pg_timestamp']).read():
IOError: [Errno 2] No such file or directory: '~/gis/planet_osm_pg.timestamp'
```

But the file _does exist!_

```
total 2476660
drwxrwxr-x  2 arch arch       4096 Jan 17 16:18 .
drwxr-xr-x 12 arch arch       4096 Jan 20 15:21 ..
-rw-rw-r--  1 arch arch         21 Jan 20 17:07 planet_osm_pg.timestamp
-rw-rw-r--  1 arch arch 2536079447 Jan 20 13:58 synth.o5m
```

(the username is not related to the flavour of linux)

**Comment by Komzpa** [comment]
~ can't be used in pythonish paths. try the full one?

**Comment by Kira-PH** [comment]
:( OK, I'll give that a go - but it's 17:25 here, so I'll update you tomorrow.

I would imagine that would also upset synthdump in an unpredictable way.

Thanks for your help!

**Comment by Kira-PH** [comment]
Works great, thanks

**Comment by Komzpa** [comment]
Thanks for the feedback!
